### ISSUE TITLE
AttributeError: 'function' object has no attribute 'write'

### ISSUE THREAD

**Issue by sio** [pycontribs/subprocess-tee#38]
subprocess_tee 0.3.1 introduces an attribute error that was not present in 0.2.0:

```
Task exception was never retrieved
future: <Task finished coro=<_read_stream() done, defined at /root/venv/lib/python3.7/site-packages/subprocess_tee/__init__.py:21> exception=AttributeError("'function' object has no attribute 'write'")>
Traceback (most recent call last):
  File "/root/venv/lib/python3.7/site-packages/subprocess_tee/__init__.py", line 25, in _read_stream
    callback(line)
  File "/root/venv/lib/python3.7/site-packages/subprocess_tee/__init__.py", line 86, in <lambda>
    _read_stream(process.stderr, lambda l: tee_func(l, err, stderr))
  File "/root/venv/lib/python3.7/site-packages/subprocess_tee/__init__.py", line 73, in tee_func
    print(line_str, file=pipe)
AttributeError: 'function' object has no attribute 'write'
```

Full molecule log: https://cirrus-ci.com/task/4613075711033344?logs=test#L247

**Comment by sio** [comment]
I can not reproduce this anymore. I think it was some incompatibility issue with an older molecule version. Latest molecule works fine.
