### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'MainThread'.

### ISSUE THREAD

**Issue by jaraco** [pycontribs/subprocess-tee#85]
I'm attempting to use subprocess tee in a simple, synchronous application, but when I run it in [this code](https://github.com/jaraco/safety-tox/blob/4fe1802590655fca1430f85cc65019c7be580b95/safety-tox.py), it fails with the following traceback:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.3/x64/lib/python3.12/site-packages/safety-tox.py", line 54, in <module>
    __name__ == '__main__' and run(sys.argv[1:])
                               ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.3/x64/lib/python3.12/site-packages/safety-tox.py", line 51, in run
    raise SystemExit(Handler().run(args))
                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.3/x64/lib/python3.12/site-packages/safety-tox.py", line 33, in run
    proc = self.runner(cmd)
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.3/x64/lib/python3.12/site-packages/subprocess_tee/__init__.py", line 138, in run
    loop = asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.3/x64/lib/python3.12/asyncio/events.py", line 676, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

I'm using Python 3.12 alpha because that's the environment where safety-tox is needed. I can't replicate the issue on Python 3.11.

Here's a reproducer without safety-tox:

```
 ~ $ py -3.12 -m pip-run subprocess-tee -- -c "from subprocess_tee import run; run(['echo', 'foo'])"
Collecting subprocess-tee
  Using cached subprocess_tee-0.4.0-py3-none-any.whl (5.1 kB)
Installing collected packages: subprocess-tee
Successfully installed subprocess-tee-0.4.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-hroxhf41/subprocess_tee/__init__.py", line 138, in run
    loop = asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 676, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

Possibly this issue should be reported upstream with CPython?

**Comment by ssbarnea** [comment]
BTW, I am very interested about finding a solution for splitting the output when running multiple tox jobs. I do have lots of reasons to want to chain multiple tox environments into a single GHA runner and the current behaviour of `tox -e foo,bar,baz` makes it hard to debug failures.

**Comment by ssbarnea** [comment]
I am unable to reproduce it with code from main branch. I suspect one of the recent changes sorted it. We also now have a py312 pipeline.
